// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AddressLocation struct {
	ID       string    `json:"id"`
	Location *Location `json:"location"`
	Address  string    `json:"address"`
	ZipCode  string    `json:"zipCode"`
}

type Company struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	Owner           *OwnerCompany    `json:"owner"`
	TaxNumber       string           `json:"tax_number"`
	Location        *Location        `json:"location"`
	AddressLocation *AddressLocation `json:"addressLocation"`
	Franchises      []*Franchise     `json:"franchises"`
}

type Franchise struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	URL             string           `json:"url"`
	Company         *Company         `json:"company"`
	Location        *Location        `json:"location"`
	AddressLocation *AddressLocation `json:"addressLocation"`
}

type FranchiseCriteria struct {
	Name *string `json:"name,omitempty"`
}

type FranchisesCriteria struct {
	Name     *string           `json:"name,omitempty"`
	Company  *string           `json:"company,omitempty"`
	Location *LocationCriteria `json:"location,omitempty"`
}

type Location struct {
	ID      string `json:"id"`
	City    string `json:"city"`
	State   string `json:"state"`
	Country string `json:"country"`
}

type LocationCriteria struct {
	City    *string `json:"city,omitempty"`
	State   *string `json:"state,omitempty"`
	Country *string `json:"country,omitempty"`
}

type NewFranchise struct {
	URL string `json:"url"`
}

type OwnerCompany struct {
	ID              string           `json:"id"`
	Name            string           `json:"name"`
	FirstName       string           `json:"firstName"`
	LastName        string           `json:"lastName"`
	Email           string           `json:"email"`
	Phone           string           `json:"phone"`
	Location        *Location        `json:"location"`
	AddressLocation *AddressLocation `json:"addressLocation"`
}

type UpdateFranchise struct {
	URL     *string `json:"url,omitempty"`
	Name    *string `json:"name,omitempty"`
	Company *string `json:"company,omitempty"`
}
